#!/usr/bin/env bash
# Display Best School 10 times using while loop
count = 1
while [ $coung -le 10 ]; do 
    if [ $count -eq 4 ]; then
        echo "bad luck"
    else if [ $count -eq 8 ]; do
        echo "good luck"
    else 
        echo "Best School"
    fi 
    count=$((count+1))
done
