#!/usr/bin/env bash
#Display Hours and Minutes
hour=0
minute=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minute -le 59 ]; do
		echo $minute
		((minute++))
	done
	minute=1
	((hour++))
done
